'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useAuth } from '@/lib/auth-context';
import { apiRequest } from '@/lib/api';
import { PrivacyResponse } from '@/components/privacy-response';
import documents from '@/lib/legal-documents.json';
export default function Page() {
  const { user } = useAuth(); const [type, setType] = useState('ACCESS'); const [description, setDescription] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const [requests, setRequests] = useState<any[]>([]); const [adminRequests, setAdminRequests] = useState<any[]>([]);
  async function refresh() { setRequests(await apiRequest<any[]>('/legal/requests')); if (user?.role === 'SUPERADMIN') setAdminRequests(await apiRequest<any[]>('/legal/admin/requests')); }
  useEffect(() => { if (user) refresh().catch(() => setMessage('Não foi possível carregar as solicitações.')); }, [user?.id]);
  async function submit(e: React.FormEvent) { e.preventDefault(); setBusy(true); setMessage(''); try { const result = await apiRequest<{ protocol: string; message: string }>('/legal/requests', { method: 'POST', body: JSON.stringify({ type, description }) }); setMessage(`${result.message} Protocolo: ${result.protocol}`); setDescription(''); await refresh(); } catch (err) { setMessage(err instanceof Error ? err.message : 'Falha ao registrar.'); } finally { setBusy(false); } }
  async function download() { setBusy(true); try { const data = await apiRequest('/legal/export'); const url = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' })); const a = document.createElement('a'); a.href = url; a.download = 'meus-dados.json'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); } catch (err) { setMessage(err instanceof Error ? err.message : 'Falha ao exportar.'); } finally { setBusy(false); } }
  return <div className="space-y-6 py-6 text-sm"><h1 className="text-2xl font-bold">Central de privacidade</h1><p className="rounded-xl border border-amber-500/40 p-4 text-amber-200">{documents.notice}</p><div className="flex gap-6 text-amber-400 underline"><Link href="/termos">Termos de uso</Link><Link href="/privacidade">Política de privacidade</Link></div><p>O e-mail fictício dos documentos não recebe mensagens. Use o formulário interno para registrar uma solicitação com protocolo. A administração precisa analisar e responder; o registro não significa que os dados foram excluídos.</p>
    {!user ? <Link href="/login" className="block text-amber-400 underline">Entre para consultar e solicitar seus dados</Link> : <><button disabled={busy} onClick={download} className="rounded-xl border border-amber-500 p-3">Baixar dados de conta, perfil e publicações</button><p>A exportação é parcial. Para outros dados pessoais, registre um pedido de acesso.</p><form onSubmit={submit} className="space-y-4"><label className="block">Tipo de solicitação<select value={type} onChange={e => setType(e.target.value)} className="mt-2 block w-full rounded-xl bg-stone-900 p-3"><option value="ACCESS">Acesso a dados</option><option value="CORRECTION">Correção</option><option value="DELETION">Exclusão</option><option value="CONSENT">Informações sobre consentimento</option><option value="OTHER">Outra solicitação</option></select></label><label className="block">Detalhes (não envie documentos ou senhas)<textarea maxLength={1000} value={description} onChange={e => setDescription(e.target.value)} className="mt-2 block w-full rounded-xl bg-stone-900 p-3" /></label><button disabled={busy} className="rounded-xl bg-amber-400 p-3 font-bold text-black">Registrar solicitação</button></form><p role="status" className="break-words">{message}</p><h2 className="text-lg font-bold">Meus protocolos</h2>{requests.length === 0 && <p>Nenhuma solicitação registrada.</p>}{requests.map(r => <div key={r.id} className="break-words rounded-xl border border-stone-700 p-3"><p>{r.id}</p><p>{r.details?.type} — {r.details?.status}</p>{r.details?.response && <p className="mt-2 whitespace-pre-wrap">Resposta: {r.details.response}</p>}<p>{new Date(r.createdAt).toLocaleString('pt-BR')}</p></div>)}{user.role === 'SUPERADMIN' && <section className="space-y-3"><h2 className="text-lg font-bold">Fila de solicitações — administração</h2><p>Analise os pedidos por este protocolo. Este painel não executa exclusão nem registra conclusão automática.</p>{adminRequests.map(r => <div key={r.id} className="break-words rounded-xl border border-stone-700 p-3"><p>{r.id} — {r.details?.status}</p><p>{r.user?.email} — {r.details?.type}</p><p className="whitespace-pre-wrap">{r.details?.description}</p>{r.details?.response && <p className="whitespace-pre-wrap">Última resposta: {r.details.response}</p>}<PrivacyResponse id={r.id} onSaved={refresh} /></div>)}</section>}</>}
  </div>;
}
