import { Post, Patron, FlirtNote, Meetup, BarEvent, Promotion, Conversation, Message, Restaurant, User, Story } from './types';

export const MOCK_RESTAURANT: Restaurant = {
  id: 'rest-pirambeira-001',
  name: 'Restaurante Pirambeira',
  slug: 'pirambeira',
  tagline: 'O boteco contemporâneo da Pituba com alma baiana',
  description:
    'Resgate dos botecos tradicionais com alta gastronomia do Chef Edu Moraes, drinks autorais por Jonathan Albuquerque e chopp Brahma com colarinho super cremoso. Música ao vivo, transmissões esportivas e a comunidade mais calorosa de Salvador.',
  address: 'Rua Guillard Muniz, 629',
  neighborhood: 'Pituba',
  city: 'Salvador',
  state: 'BA',
  phone: '(71) 98844-3210',
  instagram: '@pirambeira.bar',
  logoUrl: '/LogoPirambeiraSemFundo.png',
  coverUrl: 'https://images.unsplash.com/photo-1543007630-9710e4a00a20?auto=format&fit=crop&w=1600&q=80',
  rating: 4.9,
  activePeopleCount: 87,
  openingHours: {
    'Quarta-feira': '17:00 às 00:00',
    'Quinta-feira': '17:00 às 00:00',
    'Sexta-feira': '17:00 às 01:00',
    'Sábado': '14:00 às 01:00',
    'Domingo': '14:00 às 22:00',
  },
  menuCategories: [
    {
      name: 'Petiscos do Chef Edu Moraes',
      items: [
        { name: 'Coxinha Cremosa de Frango com Catupiry Real (6 un)', price: 'R$ 38,00', description: 'Empanadas na farinha panko artesanal com molho de pimenta doce' },
        { name: 'Dadinhos de Tapioca com Geleia de Pimenta Biquinho', price: 'R$ 34,00', description: 'Crocantes por fora, macios por dentro com queijo coalho curado' },
        { name: 'Carne de Sol Acebolada com Macaxeira na Manteiga de Garrafa', price: 'R$ 68,00', description: 'Acompanha farofa de biju e vinagrete da casa' },
        { name: 'Pastéis de Camarão com Queijo Coalho (4 un)', price: 'R$ 44,00', description: 'Recheio farto de camarões salteados e massa estaladiça' },
      ],
    },
    {
      name: 'Drinks & Chopp por Jonathan Albuquerque',
      items: [
        { name: 'Chopp Brahma Caneca Ultracongelada (350ml)', price: 'R$ 11,90', description: 'Colarinho cremoso servido a -2°C' },
        { name: 'Caju Amigo Piramba', price: 'R$ 32,00', description: 'Cachaça artesanal envelhecida, compota caseira de caju e limão siciliano' },
        { name: 'Gin Tônica Pituba Tropical', price: 'R$ 36,00', description: 'Gin premium, maracujá fresco, redução de manga e ramo de alecrim' },
        { name: 'Caipirinha Tradicional de Limão Taiti', price: 'R$ 26,00', description: 'Feita com cachaça baiana de alambique e açúcar cristal orgânico' },
      ],
    },
  ],
};

export const MOCK_CURRENT_USER: User = {
  id: 'user-ramon-001',
  email: 'ramon@tonopiramba.com.br',
  role: 'RESTAURANT_ADMIN',
  status: 'ACTIVE',
  profile: {
    id: 'prof-ramon-001',
    name: 'Ramon Cerqueira',
    username: 'RamonCerqueira',
    bio: 'Frequentador fiel do Pirambeira. Apaixonado por chopp gelado, MPB e boas conversas.',
    city: 'Salvador, BA',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    coverUrl: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1200&q=80',
    interests: ['Tecnologia', 'Chopp Brahma', 'Samba', 'Pituba', 'Gastronomia'],
    checkInCount: 14,
    showInFlirtRadar: true,
    allowFlirtFrom: 'ALL',
    invisibleMode: false,
  },
};

export const MOCK_PATRONS: Patron[] = [
  {
    checkInId: 'chk-0',
    userId: 'user-ramon-001',
    name: 'Ramon Cerqueira',
    username: 'RamonCerqueira',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    bio: 'Frequentador fiel do Pirambeira. Chopp gelado e boas conversas.',
    city: 'Salvador, BA',
    interests: ['Chopp Brahma', 'Samba', 'Pituba'],
    checkInCount: 14,
    showInFlirtRadar: true,
    startedAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    timePresentMinutes: 35,
  },
  {
    checkInId: 'chk-1',
    userId: 'user-larissa-002',
    name: 'Larissa Bahia',
    username: 'laribahia',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80',
    bio: 'Jornalista, ciclista e fã incondicional da feijoada de sábado do Piramba.',
    city: 'Salvador, BA',
    interests: ['Música Brasileira', 'Ciclismo', 'Cerveja Artesanal', 'Praia'],
    checkInCount: 9,
    showInFlirtRadar: true,
    startedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    timePresentMinutes: 45,
  },
  {
    checkInId: 'chk-2',
    userId: 'user-lucas-003',
    name: 'Lucas Ferreira',
    username: 'lucas_ferreira',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    bio: 'Publicitário na Pituba, apreciador de drinks clássicos e futebol com a galera.',
    city: 'Salvador, BA',
    interests: ['Futebol', 'Design', 'Drinks Autoriais', 'Boteco'],
    checkInCount: 18,
    showInFlirtRadar: true,
    startedAt: new Date(Date.now() - 72 * 60 * 1000).toISOString(),
    timePresentMinutes: 72,
  },
  {
    checkInId: 'chk-3',
    userId: 'user-camila-004',
    name: 'Camila Peixoto',
    username: 'camilapeixoto',
    avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=400&q=80',
    bio: 'Médica veterinária, adoro a energia deste lugar nas sextas!',
    city: 'Salvador, BA',
    interests: ['Animais', 'Gastronomia', 'Vinho & Chopp', 'MPB'],
    checkInCount: 6,
    showInFlirtRadar: true,
    startedAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    timePresentMinutes: 25,
  },
  {
    checkInId: 'chk-4',
    userId: 'user-tiago-005',
    name: 'Tiago Menezes',
    username: 'tiagomenezes',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    bio: 'Engenheiro e torcedor do Bahia. Sexta é lei bater ponto no Piramba.',
    city: 'Salvador, BA',
    interests: ['Esportes', 'Cerveja Gelada', 'Tecnologia'],
    checkInCount: 22,
    showInFlirtRadar: false,
    startedAt: new Date(Date.now() - 95 * 60 * 1000).toISOString(),
    timePresentMinutes: 95,
  },
  {
    checkInId: 'chk-5',
    userId: 'user-beatriz-006',
    name: 'Beatriz Castro',
    username: 'biacastro',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
    bio: 'Fotógrafa e apaixonada pelas noites de Salvador.',
    city: 'Salvador, BA',
    interests: ['Fotografia', 'Artes', 'Samba', 'Drinks'],
    checkInCount: 11,
    showInFlirtRadar: true,
    startedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    timePresentMinutes: 15,
  },
  {
    checkInId: 'chk-6',
    userId: 'user-diego-007',
    name: 'Diego Alcantara',
    username: 'diego_alcantara',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=400&q=80',
    bio: 'Músico e produtor cultural. Sempre na mesa do fundo afinando o violão.',
    city: 'Salvador, BA',
    interests: ['Música', 'Violão', 'Cerveja', 'Amizades'],
    checkInCount: 15,
    showInFlirtRadar: true,
    startedAt: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
    timePresentMinutes: 110,
  },
];

// Postagens EXCLUSIVAS do Bar (para a página inicial "O que está rolando")
export const MOCK_BAR_POSTS: Post[] = [
  {
    id: 'post-bar-1',
    content: '🔥 Sextou com a casa cheia no Piramba! Nosso bartender preparando o autêntico Caju Amigo defumado na pressão. Chega pra cá que a noite está só começando! 🍹🍻',
    type: 'FEED',
    createdAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    likesCount: 142,
    commentsCount: 18,
    userReaction: 'CHEERS',
    isVideo: true,
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-bartender-pouring-a-drink-into-a-glass-41484-large.mp4',
    videoDuration: '0:30',
    isBarOfficial: true,
    media: ['https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1000&q=80'],
    author: {
      id: 'bar-official-001',
      name: 'Pirambeira Bar',
      username: 'pirambeira.bar',
      avatarUrl: '/LogoPirambeiraSemFundo.png',
      checkInCount: 150,
      isOfficial: true,
    },
    comments: [
      {
        id: 'comm-b1',
        content: 'Esse drink defumado é uma obra de arte! Chegando em 15 minutos!',
        createdAt: new Date(Date.now() - 6 * 60 * 1000).toISOString(),
        author: {
          id: 'user-larissa-002',
          name: 'Larissa Bahia',
          username: 'laribahia',
          avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80',
        },
      },
    ],
  },
  {
    id: 'post-bar-2',
    content: '✨ O clima ao vivo na varanda do Piramba! Luz ambiente, boa conversa e os melhores drinks autorais da orla de Salvador. Vem curtir com a gente! 🍸🎷',
    type: 'FEED',
    createdAt: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
    likesCount: 198,
    commentsCount: 24,
    userReaction: 'FIRE',
    isVideo: true,
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-cocktails-glasses-on-a-tray-41487-large.mp4',
    videoDuration: '0:30',
    isBarOfficial: true,
    media: ['https://images.unsplash.com/photo-1572116469696-31de0f17cc34?auto=format&fit=crop&w=1000&q=80'],
    author: {
      id: 'bar-official-001',
      name: 'Pirambeira Bar',
      username: 'pirambeira.bar',
      avatarUrl: '/LogoPirambeiraSemFundo.png',
      checkInCount: 150,
      isOfficial: true,
    },
    comments: [],
  },
  {
    id: 'post-bar-3',
    content: '🦐 Especialidade do dia do Chef Edu Moraes: Pastéis de camarão crocantes com queijo coalho e vinagrete de manga. Combinação perfeita com chopp gelado a -2°C!',
    type: 'FEED',
    createdAt: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
    likesCount: 115,
    commentsCount: 14,
    userReaction: 'CHEERS',
    isBarOfficial: true,
    media: ['https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1000&q=80'],
    author: {
      id: 'bar-official-001',
      name: 'Pirambeira Bar',
      username: 'pirambeira.bar',
      avatarUrl: '/LogoPirambeiraSemFundo.png',
      checkInCount: 150,
      isOfficial: true,
    },
    comments: [],
  },
  {
    id: 'post-bar-4',
    content: '🎶 Roda de samba e brasilidades no deck começando! Chame os amigos e venha brindar. Dobradinha de caipirinha autoral até as 20h para quem fizer check-in no app! 🍻🥁',
    type: 'FEED',
    createdAt: new Date(Date.now() - 170 * 60 * 1000).toISOString(),
    likesCount: 164,
    commentsCount: 22,
    userReaction: 'FIRE',
    isBarOfficial: true,
    media: ['https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1000&q=80'],
    author: {
      id: 'bar-official-001',
      name: 'Pirambeira Bar',
      username: 'pirambeira.bar',
      avatarUrl: '/LogoPirambeiraSemFundo.png',
      checkInCount: 150,
      isOfficial: true,
    },
    comments: [],
  },
];

export const MOCK_POSTS: Post[] = [
  {
    id: 'post-bar-1',
    content: '🔥 Sextou com a casa cheia no Piramba! Nosso bartender preparando o autêntico Caju Amigo defumado na pressão. Chega pra cá que a noite está só começando! 🍹🍻',
    type: 'FEED',
    createdAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    likesCount: 142,
    commentsCount: 18,
    userReaction: 'CHEERS',
    isVideo: true,
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-bartender-pouring-a-drink-into-a-glass-41484-large.mp4',
    videoDuration: '0:30',
    isBarOfficial: true,
    media: ['https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1000&q=80'],
    author: {
      id: 'bar-official-001',
      name: 'Pirambeira Bar',
      username: 'pirambeira.bar',
      avatarUrl: '/LogoPirambeiraSemFundo.png',
      checkInCount: 150,
      isOfficial: true,
    },
    comments: [
      {
        id: 'comm-b1',
        content: 'Esse drink defumado é uma obra de arte! Chegando em 15 minutos!',
        createdAt: new Date(Date.now() - 6 * 60 * 1000).toISOString(),
        author: {
          id: 'user-larissa-002',
          name: 'Larissa Bahia',
          username: 'laribahia',
          avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80',
        },
      },
    ],
  },
  {
    id: 'post-1',
    content: 'Que noite incrível no Piramba! 🍻 Drinks autorais, amigos reunidos e aquele clima que só esse lugar tem! 🔥',
    type: 'FEED',
    createdAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    likesCount: 89,
    commentsCount: 12,
    userReaction: 'CHEERS',
    media: ['https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=1000&q=80'],
    author: {
      id: 'user-larissa-002',
      name: 'Larissa Bahia',
      username: 'larissamg',
      avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
      checkInCount: 9,
    },
    comments: [
      {
        id: 'comm-1',
        content: 'Guarda um lugar aí que estou chegando na Pituba em 10 min!',
        createdAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
        author: {
          id: 'user-lucas-003',
          name: 'Lucas Ferreira',
          username: 'lucas_ferreira',
          avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
        },
      },
      {
        id: 'comm-2',
        content: 'O colarinho do Piramba não tem igual na Bahia inteira 🔥',
        createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
        author: {
          id: 'user-tiago-005',
          name: 'Tiago Menezes',
          username: 'tiagomenezes',
          avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
        },
      },
    ],
  },
  {
    id: 'post-2',
    content: 'O Chef Edu Moraes se superou nessa carne de sol com manteiga de garrafa e macaxeira derretendo. Sexta é lei bater ponto aqui!',
    type: 'FEED',
    createdAt: new Date(Date.now() - 75 * 60 * 1000).toISOString(),
    likesCount: 54,
    commentsCount: 6,
    userReaction: 'HEART',
    media: ['https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1000&q=80'],
    author: {
      id: 'user-diego-007',
      name: 'Diego Alcantara',
      username: 'diego_alcantara',
      avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=400&q=80',
      checkInCount: 15,
    },
    comments: [],
  },
  {
    id: 'post-3',
    content: 'Deck lotado, chopp trincando a -2°C e aquele samba raiz que faz a noite valer a pena! Mesa 12 tá animada demais! 🍺🎶',
    type: 'FEED',
    createdAt: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
    likesCount: 67,
    commentsCount: 9,
    userReaction: 'CHEERS',
    media: ['https://images.unsplash.com/photo-1543807535-eceef0bc6599?auto=format&fit=crop&w=1000&q=80'],
    author: {
      id: 'user-carlos-008',
      name: 'Carlos Drummond',
      username: 'carlos_ba',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
      checkInCount: 22,
    },
    comments: [],
  },
  {
    id: 'post-bar-2',
    content: '✨ O clima ao vivo na varanda do Piramba! Luz ambiente, boa conversa e os melhores drinks autorais da orla. Vem curtir com a gente! 🍸🎷',
    type: 'FEED',
    createdAt: new Date(Date.now() - 150 * 60 * 1000).toISOString(),
    likesCount: 198,
    commentsCount: 24,
    userReaction: 'FIRE',
    isVideo: true,
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-cocktails-glasses-on-a-tray-41487-large.mp4',
    videoDuration: '0:30',
    isBarOfficial: true,
    media: ['https://images.unsplash.com/photo-1572116469696-31de0f17cc34?auto=format&fit=crop&w=1000&q=80'],
    author: {
      id: 'bar-official-001',
      name: 'Pirambeira Bar',
      username: 'pirambeira.bar',
      avatarUrl: '/LogoPirambeiraSemFundo.png',
      checkInCount: 150,
      isOfficial: true,
    },
    comments: [],
  },
  {
    id: 'post-4',
    content: 'Gin tônica de tangerina com alecrim e pimenta rosa... Impecável! Sextou em grande estilo no melhor cantinho de Salvador ✨🍸',
    type: 'FEED',
    createdAt: new Date(Date.now() - 190 * 60 * 1000).toISOString(),
    likesCount: 43,
    commentsCount: 4,
    userReaction: 'HEART',
    media: ['https://images.unsplash.com/photo-1536935338788-846bb9981813?auto=format&fit=crop&w=1000&q=80'],
    author: {
      id: 'user-camila-004',
      name: 'Camila Peixoto',
      username: 'camilapeixoto',
      avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=400&q=80',
      checkInCount: 6,
    },
    comments: [],
  },
];

export const MOCK_FLIRT_NOTES: FlirtNote[] = [
  {
    id: 'flirt-1',
    content: 'Para a pessoa de camisa de linho azul na mesa 08: seu sorriso iluminou a varanda inteira quando você chegou!',
    flirtContext: 'Mesa 08 • Varanda',
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    likesCount: 12,
    commentsCount: 2,
    author: {
      id: 'user-camila-004',
      name: 'Camila Peixoto',
      username: 'camilapeixoto',
      avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=400&q=80',
    },
  },
  {
    id: 'flirt-2',
    content: 'Quem pediu o drink Caju Amigo com duas fatias de limão siciliano no balcão tem um bom gosto impecável... Aceita um brinde?',
    flirtContext: 'Balcão de Drinks',
    createdAt: new Date(Date.now() - 65 * 60 * 1000).toISOString(),
    likesCount: 19,
    commentsCount: 4,
    author: {
      id: 'user-lucas-003',
      name: 'Lucas Ferreira',
      username: 'lucas_ferreira',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    },
  },
];

export const MOCK_MEETUPS: Meetup[] = [
  {
    id: 'meet-1',
    title: 'Mesa Tech, Startups & Chopp Gelado',
    description: 'Quem trampa com tecnologia, produto e design em Salvador: puxa uma cadeira na mesa 12 pra trocar uma ideia sem formalidades!',
    scheduledFor: new Date(Date.now() + 60 * 60 * 1000).toISOString(),
    status: 'ACTIVE',
    participantsCount: 5,
    isJoined: true,
    creator: {
      id: 'user-ramon-001',
      name: 'Ramon Valente',
      username: 'ramonvalente',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    },
    participants: [
      { userId: 'user-ramon-001', name: 'Ramon', avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80' },
      { userId: 'user-lucas-003', name: 'Lucas', avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80' },
      { userId: 'user-tiago-005', name: 'Tiago', avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80' },
    ],
  },
  {
    id: 'meet-2',
    title: 'Mesa Solteiros & Amigos Novos no Bar',
    description: 'Veio sozinho ou com 1 amigo e quer socializar com gente alto astral? Junta aqui na mesa redonda da entrada!',
    scheduledFor: new Date(Date.now() + 120 * 60 * 1000).toISOString(),
    status: 'SCHEDULED',
    participantsCount: 7,
    isJoined: false,
    creator: {
      id: 'user-larissa-002',
      name: 'Larissa Bahia',
      username: 'laribahia',
      avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80',
    },
    participants: [
      { userId: 'user-larissa-002', name: 'Larissa', avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80' },
      { userId: 'user-beatriz-006', name: 'Beatriz', avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80' },
    ],
  },
];

export const MOCK_EVENTS: BarEvent[] = [
  {
    id: 'event-1',
    title: 'Samba do Piramba com Roda de Choro',
    category: 'Música ao Vivo',
    description: 'Tarde e noite com os melhores sambistas de Salvador, cerveja no balde e petiscos especiais.',
    date: 'Amanhã',
    startTime: '17:30',
    coverImageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80',
    participantsCount: 42,
    isRsvpd: true,
  },
  {
    id: 'event-2',
    title: 'Transmissão Oficial: Clássico Ba-Vi em 4K',
    category: 'Transmissão Esportiva',
    description: 'Telão na varanda e chopp em dobro a cada gol marcado!',
    date: 'Domingo',
    startTime: '16:00',
    coverImageUrl: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=800&q=80',
    participantsCount: 68,
    isRsvpd: false,
  },
];

export const MOCK_PROMOTIONS: Promotion[] = [
  {
    id: 'promo-1',
    title: 'Happy Hour Exclusivo: 20% OFF no Chopp Brahma',
    discountText: '20% OFF',
    badge: 'HAPPY HOUR',
    description: 'Válido para todas as canecas de chopp consumidas hoje até às 20h30.',
    validUntil: 'Hoje às 20:30',
    terms: 'Exclusivo para frequentadores presentes com check-in ativo.',
    totalCoupons: 100,
    redeemedCount: 38,
    isAvailable: true,
    userCoupon: {
      id: 'cup-1',
      code: 'PIRAMBA-CHOPP-8924',
      status: 'CLAIMED',
      claimedAt: new Date().toISOString(),
    },
  },
  {
    id: 'promo-2',
    title: 'Rodada Dupla de Caipirinha na Mesa',
    discountText: '2x1',
    badge: 'DOBRO',
    description: 'Peça uma Caipirinha de Alambique e ganhe a segunda por conta do Piramba.',
    validUntil: 'Hoje às 22:00',
    terms: 'Limitado a 1 cupom por mesa.',
    totalCoupons: 50,
    redeemedCount: 41,
    isAvailable: true,
    userCoupon: null,
  },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv-1',
    type: 'MATCH',
    restaurantName: 'Restaurante Pirambeira',
    restaurantSlug: 'pirambeira',
    updatedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    otherUser: {
      id: 'user-larissa-002',
      name: 'Larissa Bahia',
      username: 'laribahia',
      avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80',
    },
    lastMessage: {
      content: 'Que coincidência massa! Vamos pedir um chopp juntos?',
      createdAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
      isMine: false,
      isRead: true,
    },
  },
];

export const MOCK_MESSAGES: Message[] = [
  {
    id: 'msg-1',
    content: 'Oi! Vi sua nota no Mural da Paquera, achei muito criativa haha',
    createdAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    isMine: false,
    isRead: true,
    senderName: 'Larissa Bahia',
  },
  {
    id: 'msg-2',
    content: 'Opa, que bom que você viu! Estou aqui perto da varanda tomando um chopp.',
    createdAt: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
    isMine: true,
    isRead: true,
  },
  {
    id: 'msg-3',
    content: 'Que coincidência massa! Vamos pedir um chopp juntos?',
    createdAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    isMine: false,
    isRead: true,
    senderName: 'Larissa Bahia',
  },
];

export const MOCK_STORIES: Story[] = [
  {
    id: 'story-bar-hoje',
    mediaUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1080&q=80',
    caption: '🎶 Roda de samba ao vivo no deck externo! Chopp em dobro rolando até as 20h 🔥',
    createdAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    author: {
      id: 'bar-official-001',
      name: 'Pirambeira Bar',
      username: 'pirambeira.bar',
      avatarUrl: '/LogoPirambeiraSemFundo.png',
      isOfficial: true,
    },
  },
  {
    id: 'story-bar-drinks',
    mediaUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=1080&q=80',
    caption: '🍹 Novos drinks autorais saindo agora no balcão! Caju Amigo defumado na pressão.',
    createdAt: new Date(Date.now() - 75 * 60 * 1000).toISOString(),
    author: {
      id: 'bar-official-001',
      name: 'Pirambeira Bar',
      username: 'pirambeira.bar',
      avatarUrl: '/LogoPirambeiraSemFundo.png',
      isOfficial: true,
    },
  },
  {
    id: 'story-user-larissa',
    mediaUrl: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1080&q=80',
    caption: 'Mesa 12 comemorando com chopp trincando e petiscos! O melhor de Salvador 🍻✨',
    createdAt: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
    author: {
      id: 'user-larissa-002',
      name: 'Larissa Bahia',
      username: 'laribahia',
      avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80',
    },
  },
  {
    id: 'story-user-lucas',
    mediaUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=1080&q=80',
    caption: 'DJ no comando com o melhor da MPB e brasilidades 🎧🔥',
    createdAt: new Date(Date.now() - 140 * 60 * 1000).toISOString(),
    author: {
      id: 'user-lucas-003',
      name: 'Lucas Ferreira',
      username: 'lucas_ferreira',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    },
  },
];

